In this module we are going to learn to handle datasets, creating , reading from external files , modifying , summarising and visualising  in python with  packages numpy , pandas and seaborn .  this first video focuses on pacakge numpy . Through numpy we will learn to create and handle arrays. Functions that we'll learn here will serve a major purpose

* They will set background for handling columns in our datasets when we eventually move to pandas dataframes


In this video we are going to look at following aspect of numpy arrays
    
    a. creating nd arrays
    
	b. subsetting with indices and conditions
    
    c. comparison with np and math functions [np.sqrt , log etc ], special numpy functions  

Lets get started with creating  two dimensional arrays . Technically you can create arrays with more than two dimensions, but we dont need them for the purpose of this course or most of the machine learning algorithms even the ones which are not covered in the course


In [1]:
import numpy as np

In [2]:
b = np.array([[3,20,99],[-13,4.5,26],[0,-1,20],[5,78,-19]])   
b

array([[  3. ,  20. ,  99. ],
       [-13. ,   4.5,  26. ],
       [  0. ,  -1. ,  20. ],
       [  5. ,  78. , -19. ]])

In [3]:
type(b)

numpy.ndarray

In [4]:
temp_list = [[3,20,99],[-13,4.5,26],[0,-1,20],[5,78,-19]]
print(type(temp_list))
print(temp_list)

<class 'list'>
[[3, 20, 99], [-13, 4.5, 26], [0, -1, 20], [5, 78, -19]]


In [5]:
temp_b = np.array(temp_list)
print(type(temp_b))
print(temp_b)

<class 'numpy.ndarray'>
[[  3.   20.   99. ]
 [-13.    4.5  26. ]
 [  0.   -1.   20. ]
 [  5.   78.  -19. ]]


b here is a 2 dimensional array , you can quickly determine size of each dimension by looking at shape attribute of an array 

In [6]:
b.shape

(4, 3)

dimension in numpy arrays are refered as axis, 2d arrays have two axis , labeled as 0 and 1. 

Since there are two dimension here we'll need to pass double indices while accessing them. counting along both the axes starts with 0

if we want to extract value -1 from the array created above , we will need to access it with its indices across both the axes. which are 2 and 1

In [7]:
b

array([[  3. ,  20. ,  99. ],
       [-13. ,   4.5,  26. ],
       [  0. ,  -1. ,  20. ],
       [  5. ,  78. , -19. ]])

In [8]:
b[2,1]

-1.0

For better understanding we can consider the first index to be index of the list where the element is , and second to be its index within that list. Indexing and slicing here works just as it worked for lists , just in two dimensions. lets look at few more examples

In [9]:
print(b)
b[:,1]

[[  3.   20.   99. ]
 [-13.    4.5  26. ]
 [  0.   -1.   20. ]
 [  5.   78.  -19. ]]


array([20. ,  4.5, -1. , 78. ])

as you can see , this simply gives us 2nd element from all the lists, and this gives us all the elements from the 2nd ist

In [10]:
b[1,:]

array([-13. ,   4.5,  26. ])

by default you can access all the elements of a single list in a 2d array by providing a single index as well

In [11]:
b[1]

array([-13. ,   4.5,  26. ])

you can pass lists of indices as well to access multiple elements of a 2d array

In [12]:
b

array([[  3. ,  20. ,  99. ],
       [-13. ,   4.5,  26. ],
       [  0. ,  -1. ,  20. ],
       [  5. ,  78. , -19. ]])

In [13]:
b[[0,1,1],[1,2,1]]

array([20. , 26. ,  4.5])

here elements will come from pairing of indices , (0,1) , (1,2) and (1,1)

you can use thin index access for modification as well

In [14]:
print(b)
b[[0,1,1],[1,2,1]]=[-10,-20,-30]
print(b)

[[  3.   20.   99. ]
 [-13.    4.5  26. ]
 [  0.   -1.   20. ]
 [  5.   78.  -19. ]]
[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


you can see that corresponding elements are now changed to new values 

you subset an array on the basis of condition also

In [15]:
b

array([[  3., -10.,  99.],
       [-13., -30., -20.],
       [  0.,  -1.,  20.],
       [  5.,  78., -19.]])

In [16]:
b>0

array([[ True, False,  True],
       [False, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [17]:
#object[condition]
b[b>0] # select values from object b which satisfies the condition

array([ 3., 99., 20.,  5., 78.])

In [18]:
#object[condition]
b[b==0] # select values from object b which satisfies the condition

array([0.])

In [19]:
b

array([[  3., -10.,  99.],
       [-13., -30., -20.],
       [  0.,  -1.,  20.],
       [  5.,  78., -19.]])

In [20]:
b[2]>=0

array([ True, False,  True])

In [22]:
print(b)
b[:,[0,2]]

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


array([[  3.,  99.],
       [-13., -20.],
       [  0.,  20.],
       [  5., -19.]])

In [21]:
print(b)
b[:,b[2]>=0]

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


array([[  3.,  99.],
       [-13., -20.],
       [  0.,  20.],
       [  5., -19.]])

keep in mind that applied condition should match in dimension size to which it is being applied if we want to apply it across a single dimension

In [26]:
b

array([[  3., -10.,  99.],
       [-13., -30., -20.],
       [  0.,  -1.,  20.],
       [  5.,  78., -19.]])

In [25]:
[b>0]

[array([[ True, False,  True],
        [False, False, False],
        [False, False,  True],
        [ True,  True, False]])]

In [24]:
  b==[b>0]

array([[[False, False, False],
        [False, False, False],
        [ True, False, False],
        [False, False, False]]])

In [23]:
b[2]>=0

array([ True, False,  True])

this condition gets applied across all the lists and they have dimension size as 3 

if we wanted to apply the condition to first element of each list and then wanted to keep all corresponding elements across lists, we will have to write it like this 

In [27]:
b

array([[  3., -10.,  99.],
       [-13., -30., -20.],
       [  0.,  -1.,  20.],
       [  5.,  78., -19.]])

In [ ]:
b[:,2]>=0

In [ ]:
print(b)
b[b[:,2]>=0,:]

If we wanted to apply functions which work on multiple values or across a full dimension instead of single value , we will need to use numpy function instead of math package function because they work on scalars of single values . Lets try using them anyway , lets say we wanted to replace the entire 2nd list ( index =1 ) with its aboslute values.

In [ ]:
import math as m


In [ ]:
b[1]

In [ ]:
m.fabs(b[1])

In [ ]:
b[1]=m.fabs(b[1])

In [ ]:
np.abs(b[1])

In [ ]:
print(b)
b[1]=np.abs(b[1])
print(b)

there are multiple such functions available in numpy you can write np. and then hit tab to show you the list of such functions 

In [ ]:
print(b)
b[1]=np.sqrt(b[1])
print(b)

these functions can work across dimensions or multiple values at once 

to better understand idea of axis labels 0 and 1 , we will look at a function which collapses the array 

In [28]:
b

array([[  3., -10.,  99.],
       [-13., -30., -20.],
       [  0.,  -1.,  20.],
       [  5.,  78., -19.]])

In [29]:
np.sum(b)

112.0

this simply sums the entire array , now lets instead of this we wanted sum across axis 0 

In [ ]:
b

In [30]:
print(b)
np.sum(b,axis=0)

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


array([-5., 37., 80.])

axis 0 here corresponds to elements across the lists , axis=1 corresponds to with in the list elements 

In [31]:

print(b)
np.sum(b,axis=1)

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


array([ 92., -63.,  19.,  64.])

As note keep in mind that when we start to work with pandas dataframes which are in a way 2d numpy arrays , each list will correspond to a column in the data. In that respect you can say axis=0 represent rows and axis=1 represent columns of a data frame

Next we will look at a small subset of numpy functions which are commonly used a lot , rarely used functions of numpy we will learn about as and when we comes across their specific use cases 

These functions help in quickly creating special kind of numpy arrays

In [32]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [34]:
np.arange(2,8,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

As you can see arange function can be used to create sequence of integers with increment of 1. For creating a more custom sequence we can use linspace

In [39]:
np.linspace(start=2,stop=10,num=5)

array([ 2.,  4.,  6.,  8., 10.])

a
a+s
a+2s
.
.
.
.
.
a+(n-1)*s


b=a+(n-1)*s

s=(b-a)/(n-1)


In [ ]:
(10-2)/14

here argument num essentially represent number of elements in sequence , elements in sequence are natuarlly equally spaced .

you can also create new arrays by randomly sampling an original array, or simply creating an array with random numbers using random package within numpy

In [41]:
np.random.randint(high=10,low=1,size=(2,3))

array([[1, 3, 3],
       [4, 1, 1]])

In [42]:
np.random.randint(high=10,low=1,size=(2,))

array([6, 2])

In [49]:
np.random.randint(high=10,low=1,size=2)

array([2, 4])

In [48]:
np.random.randint(high=10,low=1,size=[2])

array([6, 9])

In [45]:
np.random.random(size=(3,4))

array([[0.72963096, 0.43439222, 0.78975919, 0.76974863],
       [0.817911  , 0.46151806, 0.09644925, 0.35409799],
       [0.57199344, 0.43739619, 0.39499823, 0.03582045]])

In [50]:
x=np.arange(10)

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.random.choice(x,4)

array([7, 9, 8, 5])

In [53]:
np.random.choice(x,6,replace=False)

array([2, 7, 0, 8, 4, 1])

In [54]:
y=np.random.choice(['a','b'],6)
print(y)

['b' 'a' 'a' 'b' 'b' 'a']


In [55]:
y=np.random.choice(['a','b'],1000)


In [56]:
y

array(['b', 'b', 'b', 'a', 'b', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'b',
       'b', 'b', 'a', 'b', 'b', 'a', 'b', 'b', 'a', 'a', 'b', 'a', 'b',
       'b', 'b', 'b', 'b', 'b', 'a', 'b', 'a', 'a', 'b', 'a', 'b', 'a',
       'a', 'b', 'b', 'b', 'a', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b',
       'a', 'b', 'a', 'b', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'b',
       'b', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'b', 'a', 'a', 'b',
       'b', 'a', 'b', 'a', 'a', 'b', 'a', 'b', 'b', 'b', 'b', 'b', 'b',
       'b', 'a', 'b', 'b', 'a', 'b', 'a', 'b', 'b', 'a', 'b', 'a', 'a',
       'b', 'a', 'b', 'b', 'a', 'b', 'b', 'b', 'a', 'b', 'a', 'a', 'b',
       'a', 'b', 'a', 'a', 'a', 'a', 'b', 'b', 'a', 'a', 'a', 'b', 'b',
       'b', 'b', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'a', 'a', 'a',
       'a', 'a', 'a', 'a', 'b', 'a', 'a', 'b', 'b', 'b', 'a', 'b', 'b',
       'a', 'a', 'b', 'b', 'b', 'a', 'a', 'b', 'b', 'a', 'a', 'b', 'a',
       'b', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b

In [57]:
np.unique(y,return_counts=True)

(array(['a', 'b'], dtype='<U1'), array([504, 496], dtype=int64))

by default here both a and b get picked with almost equal probability in the random sample. Although this doesnt mean that individual values are not random , but overall percentage of a and b remains almost same. We can force approx probability structure by using option p

In [58]:
y=np.random.choice(['a','b','c'],100000,p=[0.2,0.4,0.4])

In [59]:
np.unique(y,return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'),
 array([19929, 40112, 39959], dtype=int64))

Another useful function is for sorting 

In [60]:
x=np.random.randint(high=100,low=12,size=(15,))

In [61]:
x.sort()

In [62]:
x

array([17, 27, 31, 36, 39, 41, 45, 46, 57, 64, 65, 73, 76, 83, 86])

Now lets look at sorting 2darrays 

In [63]:
x=np.random.randint(high=100,low=12,size=(4,6))

In [64]:
x

array([[96, 58, 65, 20, 42, 78],
       [40, 99, 76, 12, 78, 84],
       [81, 21, 76, 83, 71, 70],
       [45, 74, 96, 58, 68, 97]])

if you simply sort it sorts each individual array without mainting any order 

In [65]:
x.sort()

In [66]:
x

array([[20, 42, 58, 65, 78, 96],
       [12, 40, 76, 78, 84, 99],
       [21, 70, 71, 76, 81, 83],
       [45, 58, 68, 74, 96, 97]])

In [78]:
x=np.random.randint(high=100,low=12,size=(4,6))
x

array([[99, 90, 56, 32, 98, 21],
       [66, 68, 97, 68, 14, 13],
       [90, 49, 21, 72, 99, 29],
       [32, 68, 37, 51, 97, 88]])

For maintaining order along either of the axis what we can do is that we can extract indices of the sorted values and reorder original array with , here is what i mean

In [79]:
x[:,2]

array([56, 97, 21, 37])

these are the 3rd elements of all arrays , lets i want to sort my 2darray by these and other values should move with them maintaining correspondence

In [81]:

x[:,2].argsort() # 

array([2, 3, 0, 1], dtype=int64)

what argsort does is that it gives indices of sorted elements , now we can arrange the list along another axes using the result of argsort like this 

In [70]:
x[x[:,2].argsort(),:]

array([[81, 65, 18, 94, 97, 77],
       [39, 55, 29, 98, 84, 38],
       [44, 60, 69, 44, 64, 69],
       [35, 48, 86, 53, 67, 41]])

you can see that correspondence doesnt break here

similar to sort and argsort , another use ful combination at times is max and argmax and its counterparts min and argmin

In [71]:
x=np.random.randint(high=100,low=12,size=(15,))

In [72]:
x

array([35, 99, 27, 43, 95, 86, 31, 99, 81, 74, 80, 70, 65, 20, 55])

In [73]:
x.max()

99

In [74]:
x.argmax()

1

We will stop our discussion on numpy , other numpy related functions which are not as often used will be discussed as and when we come across their use case. In the next video we will start with pandas , the go to package for handling datasets in python. see you in the next video